export function permittedCaller(user,profile){return user?.id==='c43bd3c2-6e3a-4228-99c7-dc95f33643f2'&&user?.email?.toLowerCase()==='chloelee@wonlyglobal.com'&&profile?.active===true&&profile?.role==='owner'}
const PLATFORMS=new Set(['youtube','instagram','facebook','tiktok','linkedin']);
const n=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:null;
const label=v=>typeof v==='string'&&!/@|https?:|sk-[\w.-]{12,}|Bearer\s|<|\d{15,}/i.test(v)?v.slice(0,100):null;
const stamp=v=>typeof v==='string'&&Number.isFinite(Date.parse(v))?v:null;
export function summarize({accounts,competitors,snapshots,posts},now=Date.now()){
 const project=(item,type)=>{const history=snapshots.filter(x=>x.subject_type===type&&x.subject_id===item.id).sort((a,b)=>Date.parse(b.captured_at)-Date.parse(a.captured_at));const latest=history[0],through=stamp(item.last_synced_at);const known=!!through;return {name:label(type==='account'?item.display_name:item.name)||'未核验名称',platform:PLATFORMS.has(item.platform?.toLowerCase())?item.platform.toLowerCase():'other',through,status:!known?'missing':now-Date.parse(through)>48*3600000?'stale':'available',followers:known?n(item.followers):null,lifetime_posts_count:known?n(item.posts_count):null,latest_snapshot:latest?{captured_at:stamp(latest.captured_at),followers:n(latest.followers),lifetime_views:n(latest.views),lifetime_likes:n(latest.likes)}:null,snapshot_count:history.length}};
 const own=accounts.map(x=>project(x,'account')),rivals=competitors.map(x=>project(x,'competitor'));
 const platforms=[...new Set(posts.map(x=>x.platform?.toLowerCase()).filter(x=>PLATFORMS.has(x)))];
 return {schema_version:'1.0',site:'socialwonly.foreverdoodle.com',generated_at:new Date(now).toISOString(),status:'available',accounts:own,competitors:rivals,published_28d:platforms.map(platform=>{const rows=posts.filter(x=>x.platform?.toLowerCase()===platform);return {platform,published_posts:rows.length,recorded_likes:rows.reduce((s,x)=>s+(n(x.likes)||0),0),recorded_views:rows.reduce((s,x)=>s+(n(x.views)||0),0),recorded_comments:rows.reduce((s,x)=>s+(n(x.comments)||0),0),recorded_shares:rows.reduce((s,x)=>s+(n(x.shares)||0),0),metric_status:'recorded_not_verified',topics:rows.slice(0,8).map(x=>label(x.title)).filter(Boolean)}}),period:{start:new Date(now-28*86400000).toISOString(),end:new Date(now).toISOString()},limits:'仅WONLY品牌自有账号及系统竞品记录。每次请求读取源数据库，不等于实时拉取社媒平台。无同步日期的默认0按未知处理；超过48小时标旧。粉丝及快照views/likes是账号累计口径，不是28天增量；published_28d是28天内已发布帖子在数据库登记的累计互动，不是这28天发生的互动。帖子指标可能是默认0或手工记录，不用于声称没有曝光或精确互动率。无最新公开内容证据时不能断言竞品当前打法，更不能编造其私域、广告预算、询盘、营收或ROI。'};
}
