import test from 'node:test';
import assert from 'node:assert/strict';
import {loadSocialLibrary} from '../supabase/functions/agent-conversation/social.mjs';
const response=(page,total=37)=>new Response(JSON.stringify({status:'available',page,total_records:total,posts:Array.from({length:Math.max(0,Math.min(20,total-(page-1)*20))},(_,i)=>({platform:'youtube',url:`https://www.youtube.com/watch?v=v${(page-1)*20+i}`,content:'x'.repeat(1500),metrics:{views:null}}))}));
test('library reads beyond first page and bounds excerpts without claiming video analysis',async()=>{const called=[];const x=await loadSocialLibrary('test',async u=>{const p=Number(new URL(u).searchParams.get('posts_page'));called.push(p);return response(p)});assert.deepEqual(called,[1,2]);assert.equal(x.records_read,37);assert.deepEqual(x.platform_counts,{youtube:37});assert.equal(x.all_stored_records_read,true);assert.equal(x.posts[0].content.length,1200);assert.equal(x.posts[0].content_truncated,true);assert.equal(x.posts[0].metrics.views,null)});
test('failed page and changing total never claim complete library',async()=>{for(const changing of [false,true]){const x=await loadSocialLibrary('test',async u=>{const p=Number(new URL(u).searchParams.get('posts_page'));return p===1?response(1):changing?response(2,38):new Response('{}',{status:503})});assert.equal(x.status,'partial');assert.equal(x.records_read,20);assert.equal(x.all_stored_records_read,false)}});
test('library caps reads at 100 and rejects duplicate public links as complete coverage',async()=>{let calls=0;const x=await loadSocialLibrary('test',async u=>{calls++;return response(Number(new URL(u).searchParams.get('posts_page')),140)});assert.equal(calls,5);assert.equal(x.records_read,100);assert.equal(x.status,'partial');const y=await loadSocialLibrary('test',async u=>{const p=Number(new URL(u).searchParams.get('posts_page'));const d=await response(p).json();if(p===2)d.posts[0].url='https://www.youtube.com/watch?v=v0';return Response.json(d)});assert.equal(y.records_read,36);assert.equal(y.all_stored_records_read,false)});

import {socialContextLabel} from '../assets/agent-seo-status.mjs';
test('coverage footer uses server counts and marks partial reads',()=>{const t=socialContextLabel({social_status:'available',social_library_status:'partial',social_library_records:20,social_library_total:37});assert.match(t,/20 \/ 37/);assert.match(t,/读取不完整/);assert.match(t,/不代表平台全部/)});
