import test from 'node:test';import assert from 'node:assert/strict';
import {resolveMaterialTurn,conciseMaterialAnswer,evidenceDifferences} from '../supabase/functions/agent-conversation/material-dialogue.mjs';
import {requestBody,validateDialogue} from '../supabase/functions/agent-conversation/policy.mjs';
import {knowledgeRoute} from '../supabase/functions/agent-conversation/knowledge-routing.mjs';
const input={action:'chat',persona:'Grace',question:'天空为什么是蓝色',history:[],materialHistory:['物料：PRIVATE-X1 内部条件']};
test('internal material context is never placed in external model messages',()=>{const b=requestBody(input,'synthetic','{}');assert.doesNotMatch(JSON.stringify(b),/PRIVATE-X1|内部条件|materialHistory/);assert.throws(()=>validateDialogue({...input,materialHistory:Array(5).fill('x')}));assert.throws(()=>validateDialogue({...input,materialHistory:[{content:'x'}]}))});
test('multiple followups retain model while replacing requested property',()=>{const a=resolveMaterialTurn('那它的材质呢？',['物料：TEST-X1 防火']);assert.equal(a.question,'物料：TEST-X1 材质');const b=resolveMaterialTurn('尺寸呢？',[a.question]);assert.equal(b.question,'物料：TEST-X1 尺寸');assert.equal(knowledgeRoute(b.question).materials,true)});
test('pagination retains query and page, details do not turn into new search',()=>{assert.equal(resolveMaterialTurn('下一页',['物料：TEST-X1 防火 第2页']).question,'物料：TEST-X1 防火 第3页');assert.equal(resolveMaterialTurn('展开',['物料：TEST-X1 防火']).detail,true)});
test('new topic breaks context and ambiguous model asks instead of guessing',()=>{assert.equal(resolveMaterialTurn('今天天气怎样',['物料：TEST-X1']).question,'今天天气怎样');assert.ok(resolveMaterialTurn('那它的尺寸呢',['物料：TEST-X1 TEST-X2']).clarification);assert.equal(resolveMaterialTurn('TEST-X2呢',['物料：TEST-X1 防火']).question,'物料：TEST-X2 防火');assert.equal(knowledgeRoute('TEST-X2的尺寸是多少').materials,true)});
const asset=(id,quote,current=true)=>({id,name:'Synthetic '+id,versionLabel:'v1',isCurrentVersion:current,document:{status:'ready',pages:[{location:'第1页',chunks:['型号：TEST-X1\n'+quote],facts:[{field:'尺寸',quote}]}]}});
test('differences are candidates with sources, history and unmatched quotations excluded',()=>{const a=asset('a','尺寸：900 mm'),b=asset('b','尺寸：950 mm');assert.match(evidenceDifferences([a,b]),/尚未判定矛盾/);assert.match(evidenceDifferences([a,b]),/Synthetic a \/ 第1页/);assert.equal(evidenceDifferences([a,asset('b','尺寸：950 mm',false)]),'');b.document.pages[0].chunks=['型号：TEST-X1'];assert.equal(evidenceDifferences([a,b]),'')});
test('coverage and no-match answers avoid dumping irrelevant materials',()=>{const d={assets:[asset('a','尺寸：900 mm')],document_coverage:{total:3,ready:1}};assert.doesNotMatch(conciseMaterialAnswer(d,'产品知识覆盖'),/900 mm/);assert.match(conciseMaterialAnswer({...d,assets:[]},'物料：不存在'),/不能据此判断该产品不存在/)});
test('concise answers keep video timestamps',()=>{const a={id:'v',name:'Synthetic clip',video:{status:'ready',segments:[{start:75,kind:'speech',text:'Synthetic words'}]}};assert.match(conciseMaterialAnswer({assets:[a]},'物料：安装视频'),/1:15 语音转写/)});
test('unrecognized followup does not silently reuse the previous property',()=>{assert.match(resolveMaterialTurn('那它适合户外吗',['物料：TEST-X1 防火']).question,/户外/);assert.doesNotMatch(resolveMaterialTurn('那它适合户外吗',['物料：TEST-X1 防火']).question,/防火/)});

test('standalone product manual request resets unrelated series context',()=>{assert.deepEqual(resolveMaterialTurn('防火门英文产品手册',['我们有哪些产品系列']),{question:'防火门英文产品手册'})});
