import test from 'node:test';import assert from 'node:assert/strict';
import {knowledgeRoute,generalSystem} from '../supabase/functions/agent-conversation/knowledge-routing.mjs';
import {searchBody,searchResult,loadWebKnowledge,sourceFooter,SEARCH_URL} from '../supabase/functions/agent-conversation/web-knowledge.mjs';
test('general science avoids business data and live search',()=>{const r=knowledgeRoute('为什么天空是蓝色的？');assert.equal(r.mode,'general');for(const k of ['crm','seo','social','research','search'])assert.equal(r[k],false);assert.match(generalSystem('Grace'),/不强行转成营销/)});
test('social question selects social sources; contextual followup preserves routing',()=>{const q='分析我们YouTube社媒表现';const r=knowledgeRoute(q);assert.equal(r.social,true);assert.equal(r.crm,false);assert.equal(knowledgeRoute('那怎么做？',[{role:'user',content:q}]).social,true)});
test('mixed internal question emits only fixed public tokens, never history or internal figures',()=>{const r=knowledgeRoute('我们预算12345，查一下墨西哥门锁最新市场',[{role:'user',content:'内部利润敏感'}]);assert.equal(r.search,true);assert.match(r.publicQuery,/Mexico/);assert.doesNotMatch(r.publicQuery,/12345|利润|预算|我们/);assert.equal(knowledgeRoute('查询客户报价最新变化').search,false)});
test('public request is bounded and search protocol requests real source metadata',()=>{const b=searchBody('今天火星探测新闻');assert.equal(b.parameters.enable_search,true);assert.equal(b.parameters.search_options.enable_source,true);assert.equal(b.input.messages.length,2);assert.throws(()=>searchBody('x'.repeat(601)))});
test('unverified no-source response cannot be marked available and URLs deduplicate',()=>{const p={output:{choices:[{finish_reason:'stop',message:{content:'summary'}}],search_info:{search_results:[{title:'a',url:'https://example.com/a'},{title:'a',url:'https://example.com/a'},{url:'javascript:alert(1)'},{url:'https://127.0.0.1/x'}]}}};const r=searchResult(p,'2026-09-24');assert.equal(r.sources.length,1);assert.equal(r.sources[0].published_at,null);assert.match(sourceFooter(r),/未独立逐页核验/);delete p.output.search_info;assert.equal(searchResult(p,'today').status,'no_sources')});
test('search unavailable is explicit; no-query never fetches and endpoint cannot be supplied by caller',async()=>{let calls=0;assert.equal((await loadWebKnowledge('','key',()=>assert.fail())).status,'not_requested');const r=await loadWebKnowledge('public','synthetic',async(url,o)=>{calls++;assert.equal(url,SEARCH_URL);assert.equal(o.redirect,'error');return new Response('',{status:500})});assert.equal(calls,1);assert.equal(r.status,'unavailable');assert.equal(r.checked_at,undefined)});
