import test from 'node:test';import assert from 'node:assert/strict';
import {livePlatforms} from '../integrations/social-summary/supabase/functions/social-summary/live-platforms.mjs';
const now=new Date('2026-09-26T12:00:00Z');
const base={now,get:()=>null,accounts:[],tiktokToken:async()=>null};
const json=d=>new Response(JSON.stringify(d));
test('no authorization produces no platform requests',async()=>{let calls=0;const r=await livePlatforms({...base,fetcher:async()=>{calls++;throw Error()}});assert.equal(calls,0);assert.equal(r.facebook.reason,'not_configured');assert.equal(r.tiktok.reason,'not_authorized')});
test('Facebook uses Page token only and rejects wrong account without reading feed',async()=>{let calls=0;const r=await livePlatforms({...base,get:k=>k==='FB_PAGE_TOKEN'?'private-token':null,accounts:[{platform:'facebook',external_id:'2'}],fetcher:async(url,opts)=>{calls++;assert.equal(opts.headers.Authorization,'Bearer private-token');assert.equal(opts.redirect,'error');assert.ok(!url.includes('private-token'));return json({id:'1'})}});assert.equal(calls,2);assert.equal(r.facebook.reason,'account_binding_mismatch');assert.ok(!JSON.stringify(r).includes('private-token'))});
test('platform token failure is sanitized and does not report successful metrics',async()=>{const r=await livePlatforms({...base,get:k=>k==='FB_PAGE_TOKEN'?'secret':null,fetcher:async()=>new Response(JSON.stringify({error:{code:190,message:'secret raw upstream'}}),{status:400})});assert.equal(r.facebook.reason,'reauthorization_required');assert.ok(!JSON.stringify(r).includes('secret'))});
test('bound Facebook feed preserves unknown and numeric zero separately',async()=>{const r=await livePlatforms({...base,get:k=>k==='FB_PAGE_TOKEN'?'token':null,accounts:[{platform:'facebook',external_id:'1'}],fetcher:async url=>url.includes('/me?')?json({id:'1'}):json({data:[{message:'hi',likes:{summary:{total_count:0}}}],paging:{next:'https://untrusted.invalid'}})});assert.equal(r.facebook.status,'available');assert.equal(r.facebook.posts[0].metrics.likes,0);assert.equal(r.facebook.posts[0].metrics.shares,null);assert.equal(r.facebook.has_more,true)});
test('expired TikTok token is never sent and wrong account never returns videos',async()=>{let calls=0;const r=await livePlatforms({...base,tiktokToken:async()=>({access_token:'token',expires_at:'2026-09-25'}),fetcher:async()=>{calls++;return json({})}});assert.equal(calls,0);assert.equal(r.tiktok.reason,'reauthorization_required')});
test('Instagram insight denial keeps published content and marks unknown values',async()=>{const r=await livePlatforms({...base,get:k=>({IG_ACCESS_TOKEN:'token',IG_BUSINESS_ID:'123'})[k],accounts:[{platform:'instagram',external_id:'123'}],fetcher:async url=>url.includes('/media?')?json({data:[{id:'42',caption:'public'}]}):new Response(JSON.stringify({error:{code:10}}),{status:403})});assert.equal(r.instagram.status,'available');assert.equal(r.instagram.insights_status,'unavailable');assert.equal(r.instagram.posts[0].metrics.reach,null);assert.equal(r.instagram.posts[0].metric_errors.reach,'permission_required')});

test('verified public TikTok handle resolves app-specific identifier without changing binding',async()=>{const r=await livePlatforms({...base,accounts:[{platform:'tiktok',external_id:'legacy',handle:'wonlyglobal'}],tiktokToken:async()=>({access_token:'token',expires_at:'2026-09-27'}),fetcher:async url=>url.includes('video/list')?json({data:{videos:[],has_more:false},error:{code:'ok'}}):json({data:{user:{open_id:'app-specific',username:'wonlyglobal'}},error:{code:'ok'}})});assert.equal(r.tiktok.status,'available')});
