import test from 'node:test';import assert from 'node:assert/strict';import {loadFullMaterials,fullMaterialAnswer} from '../supabase/functions/agent-conversation/materials.mjs';import {knowledgeRoute} from '../supabase/functions/agent-conversation/knowledge-routing.mjs';
import {MATERIAL_ACTOR,verifyMaterialRequest} from '../supabase/functions/agent-conversation/material-request-proof.mjs';
const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
const publicJwk=JSON.stringify(await crypto.subtle.exportKey('jwk',keys.publicKey));
const config={actor:MATERIAL_ACTOR,privateJwk:JSON.stringify(await crypto.subtle.exportKey('jwk',keys.privateKey)),secret:'synthetic',serviceUrl:'https://file.foreverdoodle.com:8088',question:'物料：手册'};
test('full catalogue uses the fixed source and passes body-bound signed proof; drops identities',async()=>{assert.equal(knowledgeRoute('帮我找到英语产品手册').materials,true);const result=await loadFullMaterials(config,async(url,o)=>{assert.equal(url,'https://file.foreverdoodle.com:8088/api/integrations/crm/knowledge');assert.equal(o.headers['X-CRM-Authorization'],undefined);assert.ok(await verifyMaterialRequest({proof:o.headers['X-CRM-Proof'],body:o.body,publicJwk}));assert.equal(JSON.parse(o.body).query,'手册');return Response.json({status:'available',scope:'authorized_material_library',page:1,assets:[{id:'a',name:'synthetic',visibility:'internal',uploadedBy:'PRIVATE',storedName:'PRIVATE',excerpt:'synthetic text'}]})});assert.equal(result.status,'available');assert.equal(result.assets[0].visibility,'internal');assert.equal(JSON.stringify(result.assets).includes('PRIVATE'),false);assert.match(fullMaterialAnswer(result),/没有发送给外部模型/)});
test('wrong hosts, credentials in URL, missing config and failed auth cannot return catalogue',async()=>{for(const serviceUrl of ['https://evil.example','http://file.foreverdoodle.com','https://secret@file.foreverdoodle.com',''])assert.equal((await loadFullMaterials({...config,serviceUrl},()=>assert.fail())).status,'not_configured');assert.equal((await loadFullMaterials(config,async()=>new Response('',{status:403}))).status,'unavailable')});
test('a limited marketing response cannot be represented as full catalogue',async()=>{const result=await loadFullMaterials(config,async()=>Response.json({assets:[{id:'a'}]}));assert.equal(result.status,'unavailable');assert.match(fullMaterialAnswer(result),/不能把营销资料目录当作全库/)});
test('video evidence preserves time and labels inferred frames, drops unsafe fields',async()=>{const result=await loadFullMaterials(config,async()=>Response.json({status:'available',scope:'authorized_material_library',page:1,assets:[{id:'v',name:'synthetic',type:'视频',video:{status:'partial',private:'hidden',segments:[{kind:'speech',start:65,text:'synthetic speech'},{kind:'visual_inference',start:80,text:'synthetic scene'},{kind:'instruction',start:1,text:'bad'},{kind:'speech',start:-1,text:'bad'}]}}]}));const answer=fullMaterialAnswer(result);assert.match(answer,/1:05 语音转写/);assert.match(answer,/画面推测/);assert.match(answer,/部分解析/);assert.equal(result.assets[0].video.segments.length,2);assert.equal(JSON.stringify(result).includes('hidden'),false)});
