#!/usr/bin/env bash
set -euo pipefail
# Same temporary-volume build pattern as WONLY Materials: avoids AppleDouble
# resource files generated by macOS on the external T7 volume.
grace_root="$(cd "$(dirname "$0")/.." && pwd)"
export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home}"
export GRACE_ANDROID_BUILD_ROOT="$(mktemp -d /private/tmp/grace-android-build.XXXXXX)"
cd "$grace_root/android"
./gradlew --offline --no-daemon assembleDebug
mkdir -p "$grace_root/outputs"
cp "$GRACE_ANDROID_BUILD_ROOT/app/outputs/apk/debug/app-debug.apk" "$grace_root/outputs/Grace-debug.apk"
echo "$grace_root/outputs/Grace-debug.apk"
