import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import nodemailer from "npm:nodemailer@7.0.6";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Content-Type":"application/json"};
function envKey(grouped:string,standard:string){const value=Deno.env.get(grouped);if(value){try{return JSON.parse(value).default||""}catch{}}return Deno.env.get(standard)||""}
function errorText(error:unknown){return error instanceof Error?error.message:String(error||"未知错误")}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
  const authorization=req.headers.get("Authorization")||"",url=Deno.env.get("SUPABASE_URL")||"",userClient=createClient(url,envKey("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),{global:{headers:{Authorization:authorization}}}),admin=createClient(url,envKey("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)throw new Error("未登录");
  const {data:caller,error:callerError}=await userClient.from("profiles").select("id,email,full_name,role,active").eq("id",user.id).single();if(callerError||!caller?.active||!["sales","sales_manager","owner"].includes(caller.role))throw new Error("仅业务员或销售主管可以测试个人邮箱");
  const {data:connection,error:connectionError}=await admin.from("mailbox_connections").select("id,email,smtp_host,smtp_port,status").eq("user_id",user.id).eq("mailbox_kind","personal").eq("status","connected").single();if(connectionError||!connection)throw new Error("当前业务员邮箱尚未连接");
  const {data:password,error:secretError}=await admin.rpc("read_mailbox_secret",{target_connection_id:connection.id});if(secretError||!password)throw new Error("邮箱凭据不可用，请重新连接");
  const transport=nodemailer.createTransport({host:connection.smtp_host,port:connection.smtp_port,secure:Number(connection.smtp_port)===465,auth:{user:connection.email,pass:password},connectionTimeout:15000,greetingTimeout:15000,socketTimeout:30000}),stamp=new Date().toISOString(),subject=`CRM E2E TEST - ${caller.full_name||connection.email} - ${stamp}`,text="Internal CRM end-to-end test only. Do not treat this as a real customer inquiry or follow up externally. This message verifies salesperson outbound sending, shared inquiry inbound synchronization, and communication records.";
  const sent=await transport.sendMail({from:`"${caller.full_name||connection.email}" <${connection.email}>`,to:"inquiry@wonlyglobal.com",subject,text});await admin.from("audit_logs").insert({actor_id:user.id,entity_type:"profile",entity_id:user.id,action:"mailbox_e2e_test_sent",after_data:{recipient:"inquiry@wonlyglobal.com",subject,message_id:sent.messageId||null},reason:"业务员个人邮箱收发连通性测试"});return new Response(JSON.stringify({sent:true,subject,message_id:sent.messageId||null,sent_at:stamp}),{headers:cors});
}catch(error){return new Response(JSON.stringify({error:errorText(error)}),{status:400,headers:cors})}});
