-- Order history is generated by the atomic order workflow, never by browser inserts.
revoke all on public.order_events from authenticated;
grant select on public.order_events to authenticated;
grant select,insert,update,delete on public.order_events to service_role;
