begin;

do $$
declare
  number_two public.inquiries%rowtype;
  real_second public.inquiries%rowtype;
begin
  select * into strict number_two from public.inquiries where inquiry_no = 2;
  select * into strict real_second from public.inquiries where inquiry_no = 46;

  if not number_two.excluded_from_dashboard or number_two.title !~* '(50JPRYT|Chloe)' then
    raise exception 'Inquiry 2 is not the expected quarantined warm-up record';
  end if;
  if real_second.excluded_from_dashboard or real_second.title !~* 'Mineracao Canaa' then
    raise exception 'Inquiry 46 is not the expected second real inquiry';
  end if;
end
$$;

alter table public.inquiries disable trigger inquiries_enforce_update_scope;
alter table public.inquiries alter column inquiry_no set generated by default;

do $$
declare
  number_two public.inquiries%rowtype;
  real_second public.inquiries%rowtype;
  number_two_before jsonb;
  real_second_before jsonb;
  change_reason constant text := '业务确认当前仅 #000001 和 Mineracao Canaa 为真实询盘；将后者校正为第 2 条真实询盘';
begin
  select * into strict number_two from public.inquiries where inquiry_no = 2 for update;
  select * into strict real_second from public.inquiries where inquiry_no = 46 for update;
  number_two_before := to_jsonb(number_two);
  real_second_before := to_jsonb(real_second);

  update public.inquiries set inquiry_no = -2, updated_at = clock_timestamp(), last_change_reason = change_reason where id = number_two.id;
  update public.inquiries set inquiry_no = 2, updated_at = clock_timestamp(), last_change_reason = change_reason where id = real_second.id;
  update public.inquiries set inquiry_no = 46, updated_at = clock_timestamp(), last_change_reason = change_reason where id = number_two.id;

  insert into public.audit_logs (actor_id, entity_type, entity_id, action, before_data, after_data, reason)
  select null, 'inquiry', number_two.id, 'inquiry_number_reassigned', number_two_before, to_jsonb(i), change_reason from public.inquiries i where i.id = number_two.id;
  insert into public.audit_logs (actor_id, entity_type, entity_id, action, before_data, after_data, reason)
  select null, 'inquiry', real_second.id, 'business_inquiry_number_corrected', real_second_before, to_jsonb(i), change_reason from public.inquiries i where i.id = real_second.id;
end
$$;

alter table public.inquiries alter column inquiry_no set generated always;

do $$
declare
  item public.inquiries%rowtype;
  before_row jsonb;
  after_row jsonb;
  exclusion_reason constant text := '业务确认非真实询盘：系统回环测试或重复/测试官网表单';
begin
  for item in select * from public.inquiries where inquiry_no in (7, 50, 51) order by inquiry_no for update loop
    if item.inquiry_no = 7 and item.title !~* 'CRM SYSTEM TEST' then raise exception 'Inquiry 7 is not the expected system test record'; end if;
    if item.inquiry_no = 50 and item.title <> 'New WONLY Website Enquiry' then raise exception 'Inquiry 50 is not the expected duplicate/test form record'; end if;
    if item.inquiry_no = 51 and item.title <> 'New WONLY Contact Enquiry' then raise exception 'Inquiry 51 is not the expected duplicate/test form record'; end if;

    before_row := to_jsonb(item);
    update public.inquiries
    set validity = 'invalid', invalid_reason = exclusion_reason, excluded_from_dashboard = true,
        dashboard_exclusion_reason = '系统测试或重复表单', last_change_reason = exclusion_reason,
        updated_at = clock_timestamp()
    where id = item.id returning to_jsonb(inquiries) into after_row;

    insert into public.audit_logs (actor_id, entity_type, entity_id, action, before_data, after_data, reason)
    values (null, 'inquiry', item.id, 'non_business_inquiry_excluded', before_row, after_row, exclusion_reason);
  end loop;

  update public.email_messages set association_status = 'ignored', association_method = 'non_business_test_filter'
  where inquiry_id in (select id from public.inquiries where inquiry_no in (7, 50, 51));
  delete from public.notifications where inquiry_id in (select id from public.inquiries where inquiry_no in (7, 50, 51));
end
$$;

alter table public.inquiries enable trigger inquiries_enforce_update_scope;
commit;
